/**
 * Moonlight Production - Master Template Design Registry & Configuration Engine
 * 
 * Defines the theme, colors, typography, section ordering, decorative treatments,
 * and component styles for all 20 invitation suites (10 Royal Video Suites + 10 Classic 3D Suites).
 */

export const templateRegistry = {
  // =========================================================================
  // 👑 10 ROYAL TIER SUITES (Cinematic 3D Video Gate Openings)
  // =========================================================================

  // 1. Royal Imperial
  'rose-gold-blush-royal': {
    id: 'rose-gold-blush-royal',
    slug: 'rose-gold-blush-royal',
    name: 'Royal Imperial',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Cinematic rose-gold opening with luxurious motion storytelling',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🎺 Royal Shehnai & Sitar Serenade',
    videoGate: '/videos/rose-gold-blush.mp4',
    theme: {
      style: 'royal-imperial',
      pageBg: 'bg-[#1C140E]',
      cardBg: 'bg-[#2A1D13]/95',
      accentBg: 'bg-gradient-to-r from-[#4a3410] via-[#b08820] to-[#2a1f08]',
      textPrimary: 'text-[#f5e6e0]',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-amber-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-amber-400 via-amber-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-500 to-amber-700 text-black',
      crestIcon: '👑',
      motifStyle: 'rajwada-carved',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 2. Royal Prestige
  'royal-prestige': {
    id: 'royal-prestige',
    slug: 'royal-prestige',
    name: 'Royal Prestige',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Prestigious cinematic opening with refined elegance and grandeur',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🎻 Romantic Acoustic Strings & Harp',
    videoGate: '/videos/royal-prestige.mp4',
    theme: {
      style: 'royal-prestige',
      pageBg: 'bg-[#261019]',
      cardBg: 'bg-[#3b1927]/95',
      accentBg: 'bg-gradient-to-r from-[#fde2e8] via-[#f7c2cf] to-[#fde2e8]',
      textPrimary: 'text-[#fde2e8]',
      textSecondary: 'text-pink-200/90',
      textMuted: 'text-pink-300/70',
      textAccent: 'text-rose-400',
      borderColor: 'border-rose-500/30',
      borderAccent: 'border-rose-400/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-500 to-pink-600 text-white',
      crestIcon: '🌸',
      motifStyle: 'floral-wreath',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 3. Royal Elegance
  'modern-minimal-royal': {
    id: 'modern-minimal-royal',
    slug: 'modern-minimal-royal',
    name: 'Royal Elegance',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Velvet cream and crimson cinematic experience with palace motifs',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🎻 Royal Philharmonic Sitar Symphony',
    videoGate: '/videos/royal-elegance-royal.mp4',
    theme: {
      style: 'royal-elegance',
      pageBg: 'bg-[#1a0303]',
      cardBg: 'bg-[#3a0808]/95',
      accentBg: 'bg-gradient-to-r from-[#3a0808] via-[#7a1212] to-[#1a0303]',
      textPrimary: 'text-[#fef2f2]',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-red-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-rose-400 via-amber-200 to-rose-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-red-600 to-amber-600 text-white',
      crestIcon: '👑',
      motifStyle: 'velvet-damask',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 4. Royal Majesty
  'royal-majesty': {
    id: 'royal-majesty',
    slug: 'royal-majesty',
    name: 'Royal Majesty',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Porcelain blue ballroom romance with painterly cinematic grandeur',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🏛️ Serene Grand Piano & Crystal Symphony',
    videoGate: '/videos/royal-majesty.mp4',
    theme: {
      style: 'royal-majesty',
      pageBg: 'bg-[#0b131e]',
      cardBg: 'bg-[#16253b]/95',
      accentBg: 'bg-gradient-to-r from-[#eef3f8] via-[#b4c4d6] to-[#eef3f8]',
      textPrimary: 'text-[#f1f5f9]',
      textSecondary: 'text-slate-200/90',
      textMuted: 'text-slate-300/70',
      textAccent: 'text-sky-300',
      borderColor: 'border-slate-500/30',
      borderAccent: 'border-sky-300/60',
      goldGradient: 'from-slate-200 via-white to-slate-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-slate-700 to-zinc-800 text-slate-100',
      crestIcon: '🏛️',
      motifStyle: 'marble-inlay',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 5. Royal Heritage
  'royal-heritage': {
    id: 'royal-heritage',
    slug: 'royal-heritage',
    name: 'Royal Heritage',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Timeless cinematic opening with regal heritage storytelling',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🦚 Jaipur Nagada, Sitar & Shehnai Utsav',
    videoGate: '/videos/royal-heritage.mp4',
    theme: {
      style: 'royal-heritage',
      pageBg: 'bg-[#081926]',
      cardBg: 'bg-[#0f2d44]/95',
      accentBg: 'bg-gradient-to-r from-[#d9ecf5] via-[#a8d4e8] to-[#d9ecf5]',
      textPrimary: 'text-[#e0f2fe]',
      textSecondary: 'text-sky-200/90',
      textMuted: 'text-sky-300/70',
      textAccent: 'text-sky-300',
      borderColor: 'border-sky-600/30',
      borderAccent: 'border-amber-400/60',
      goldGradient: 'from-sky-300 via-amber-200 to-sky-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-sky-600 to-indigo-800 text-amber-200',
      crestIcon: '🦚',
      motifStyle: 'jharokha-arch',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 6. Royal Legacy
  'royal-legacy': {
    id: 'royal-legacy',
    slug: 'royal-legacy',
    name: 'Royal Legacy',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Burgundy velvet curtains, antique gold ornament, and cinematic reveal',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🛡️ Grand Rajputana Trumpet & Royal Fanfare',
    videoGate: '/videos/royal-legacy.mp4',
    theme: {
      style: 'royal-legacy',
      pageBg: 'bg-[#1f0a07]',
      cardBg: 'bg-[#38130d]/95',
      accentBg: 'bg-gradient-to-r from-[#32100b] via-[#786138] to-[#32100b]',
      textPrimary: 'text-[#fef3c7]',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-amber-700/30',
      borderAccent: 'border-yellow-500/60',
      goldGradient: 'from-amber-400 via-yellow-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-600 to-yellow-600 text-black',
      crestIcon: '🛡️',
      motifStyle: 'fortress-spikes',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 7. Royal Crest
  'royal-crest': {
    id: 'royal-crest',
    slug: 'royal-crest',
    name: 'Royal Crest',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Warm ivory florals, antique burgundy wax seal, and lakeside romance',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '✨ Warm Floral Harmony & Sitar',
    videoGate: '/videos/royal-crest.mp4',
    theme: {
      style: 'royal-crest',
      pageBg: 'bg-[#1c140d]',
      cardBg: 'bg-[#332518]/95',
      accentBg: 'bg-gradient-to-r from-[#f3eadb] via-[#d4c0a7] to-[#f3eadb]',
      textPrimary: 'text-[#fef2f2]',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-amber-200',
      borderColor: 'border-amber-700/30',
      borderAccent: 'border-amber-400/60',
      goldGradient: 'from-amber-400 via-yellow-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-700 to-orange-700 text-white',
      crestIcon: '👑',
      motifStyle: 'temple-kalash',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 8. Royal Grace
  'royal-grace': {
    id: 'royal-grace',
    slug: 'royal-grace',
    name: 'Royal Grace',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Sage garden serenity with pearl drapes and graceful cinematic reveal',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3574c82c3.mp3?filename=indian-classical-instrumental-110825.mp3',
    musicTitle: '🌿 Classical Sitar & Botanical Symphony',
    videoGate: '/videos/royal-grace.mp4',
    theme: {
      style: 'royal-grace',
      pageBg: 'bg-[#0f1f18]',
      cardBg: 'bg-[#1c382c]/95',
      accentBg: 'bg-gradient-to-r from-[#f7f2e6] via-[#9aa584] to-[#f7f2e6]',
      textPrimary: 'text-[#ecfdf5]',
      textSecondary: 'text-emerald-200/90',
      textMuted: 'text-emerald-300/70',
      textAccent: 'text-emerald-300',
      borderColor: 'border-emerald-600/30',
      borderAccent: 'border-emerald-400/60',
      goldGradient: 'from-emerald-300 via-amber-200 to-teal-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-emerald-600 to-teal-700 text-white',
      crestIcon: '🌿',
      motifStyle: 'awadh-arch',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 9. Emerald Noir Royal
  'emerald-noir-royal': {
    id: 'emerald-noir-royal',
    slug: 'emerald-noir-royal',
    name: 'Emerald Noir Royal',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Imperial Emerald Green, Mughal Jaali & Gold Dynasty',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3574c82c3.mp3?filename=indian-classical-instrumental-110825.mp3',
    musicTitle: '🪈 Mughal Flute & Santoor Symphony',
    videoGate: '/videos/emerald-noir-royal.mp4',
    theme: {
      style: 'emerald-noir-royal',
      pageBg: 'bg-[#031910]',
      cardBg: 'bg-[#072a1b]/95',
      accentBg: 'bg-gradient-to-r from-[#031910] via-[#0c4630] to-[#02140c]',
      textPrimary: 'text-[#ecfdf5]',
      textSecondary: 'text-emerald-200/90',
      textMuted: 'text-emerald-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-emerald-600/30',
      borderAccent: 'border-emerald-500/60',
      goldGradient: 'from-emerald-400 via-teal-200 to-amber-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-emerald-500 to-teal-700 text-amber-200',
      crestIcon: '✨',
      motifStyle: 'jaali',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'emerald-foil',
      rsvp: 'royal-suite',
    },
  },

  // 10. Ivory Elegance Royal
  'ivory-elegance-royal': {
    id: 'ivory-elegance-royal',
    slug: 'ivory-elegance-royal',
    name: 'Ivory Elegance & Crimson Royale',
    category: 'Wedding Invitation',
    tier: 'royal',
    subtitle: 'Deep crimson, antique gold foil & royal palace portals',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🎻 Royal Philharmonic Sitar Symphony',
    videoGate: '/videos/ivory-elegance-royal.mp4',
    theme: {
      style: 'ivory-elegance-royal',
      pageBg: 'bg-[#200308]',
      cardBg: 'bg-[#3b0914]/95',
      accentBg: 'bg-gradient-to-r from-[#2a040b] via-[#5e0d1f] to-[#1a0206]',
      textPrimary: 'text-[#fff1f2]',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-rose-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-rose-400 via-amber-200 to-rose-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-600 to-amber-600 text-white',
      crestIcon: '👑',
      motifStyle: 'velvet-damask',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // =========================================================================
  // 🌸 10 CLASSIC TIER SUITES (Interactive 3D Gate Openings)
  // =========================================================================

  // 11. Pastel Floral Symphony
  'blooming-dreams': {
    id: 'blooming-dreams',
    slug: 'blooming-dreams',
    name: 'Pastel Floral Symphony',
    category: 'Engagement Invitation',
    tier: 'classic',
    subtitle: 'Soft Rose Quartz, Champagne Gold & Botanical Envelope Bloom',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🎻 Romantic Acoustic Guitar & Violin',
    theme: {
      style: 'pastel-floral',
      pageBg: 'bg-[#1F1418]',
      cardBg: 'bg-[#2E1D24]/95',
      accentBg: 'bg-gradient-to-r from-rose-500 via-rose-400 to-pink-600',
      textPrimary: 'text-rose-50',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-rose-300',
      borderColor: 'border-rose-500/30',
      borderAccent: 'border-rose-400/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-400 to-pink-600 text-white',
      crestIcon: '🌸',
      motifStyle: 'floral-wreath',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 12. Modern Minimalist Luxe
  'modern-minimal': {
    id: 'modern-minimal',
    slug: 'modern-minimal',
    name: 'Modern Minimalist Luxe',
    category: 'Wedding Invitation',
    tier: 'classic',
    subtitle: 'Frosted Glass Sliding Panels, Crisp Typography & Monogram',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🎹 Crisp Minimalist Piano & Ambient Strings',
    theme: {
      style: 'modern-minimal',
      pageBg: 'bg-[#0f1115]',
      cardBg: 'bg-[#181b22]/95',
      accentBg: 'bg-gradient-to-r from-zinc-700 via-slate-600 to-zinc-800',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-zinc-200/90',
      textMuted: 'text-zinc-300/70',
      textAccent: 'text-amber-200',
      borderColor: 'border-zinc-700/30',
      borderAccent: 'border-zinc-400/60',
      goldGradient: 'from-zinc-300 via-white to-zinc-400',
      fontHeading: 'font-sans',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-zinc-700 to-stone-800 text-white',
      crestIcon: '💎',
      motifStyle: 'geometric-diamond',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 13. Rose Gold Botanical Ribbon
  'rose-gold-blush': {
    id: 'rose-gold-blush',
    slug: 'rose-gold-blush',
    name: 'Rose Gold Botanical Ribbon',
    category: 'Engagement Invitation',
    tier: 'classic',
    subtitle: 'Silk Satin Ribbon Untie, Rose Gold Heart & Romantic Chords',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '💕 Soft Romantic Acoustic Strings & Harp',
    theme: {
      style: 'rose-gold-blush',
      pageBg: 'bg-[#180a12]',
      cardBg: 'bg-[#29121f]/95',
      accentBg: 'bg-gradient-to-r from-pink-500 via-rose-400 to-rose-600',
      textPrimary: 'text-pink-50',
      textSecondary: 'text-pink-200/90',
      textMuted: 'text-pink-300/70',
      textAccent: 'text-rose-200',
      borderColor: 'border-pink-500/30',
      borderAccent: 'border-rose-300/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-pink-500 to-rose-600 text-white',
      crestIcon: '💖',
      motifStyle: 'silk-ribbon',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 14. Celestial Starlight Galaxy
  'celestial-night': {
    id: 'celestial-night',
    slug: 'celestial-night',
    name: 'Celestial Starlight Galaxy',
    category: 'Wedding Invitation',
    tier: 'classic',
    subtitle: 'Constellation Sphere Split, Glowing Stardust & Crescent Moon',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '✨ Cosmic Crystal Shimmer & Ambient Bells',
    theme: {
      style: 'celestial-night',
      pageBg: 'bg-[#050b1b]',
      cardBg: 'bg-[#0d1730]/95',
      accentBg: 'bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-600',
      textPrimary: 'text-sky-50',
      textSecondary: 'text-sky-200/90',
      textMuted: 'text-sky-300/70',
      textAccent: 'text-sky-300',
      borderColor: 'border-sky-500/30',
      borderAccent: 'border-sky-400/60',
      goldGradient: 'from-sky-300 via-indigo-100 to-purple-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-sky-500 to-indigo-700 text-white',
      crestIcon: '🌙',
      motifStyle: 'constellation-stars',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 15. Bohemian Terracotta & Sage
  'terracotta-boho': {
    id: 'terracotta-boho',
    slug: 'terracotta-boho',
    name: 'Bohemian Terracotta & Sage',
    category: 'Wedding Invitation',
    tier: 'classic',
    subtitle: 'Artisanal Linen Tri-Fold, Terracotta Stamp & Palm Sprig',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🌿 Warm Rustic Acoustic Strings & Windchimes',
    theme: {
      style: 'terracotta-boho',
      pageBg: 'bg-[#1c100a]',
      cardBg: 'bg-[#301a11]/95',
      accentBg: 'bg-gradient-to-r from-amber-700 via-orange-600 to-stone-600',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-orange-300',
      borderColor: 'border-amber-700/30',
      borderAccent: 'border-orange-500/60',
      goldGradient: 'from-amber-400 via-orange-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-700 to-orange-700 text-white',
      crestIcon: '🌿',
      motifStyle: 'boho-palm',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 16. Marigold Henna Utsav
  'mehendi-magic': {
    id: 'mehendi-magic',
    slug: 'mehendi-magic',
    name: 'Marigold Henna Utsav',
    category: 'Wedding Invitation',
    tier: 'classic',
    subtitle: 'Kaleidoscopic Henna Mandala Bloom, Marigold & Dholak',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=energy-10657.mp3',
    musicTitle: '🌼 Joyful Folk Bells & Mehendi Dholak Beats',
    theme: {
      style: 'mehendi-magic',
      pageBg: 'bg-[#1f1001]',
      cardBg: 'bg-[#331c03]/95',
      accentBg: 'bg-gradient-to-r from-yellow-500 via-amber-500 to-orange-500',
      textPrimary: 'text-yellow-50',
      textSecondary: 'text-yellow-200/90',
      textMuted: 'text-yellow-300/70',
      textAccent: 'text-yellow-300',
      borderColor: 'border-yellow-500/30',
      borderAccent: 'border-amber-400/60',
      goldGradient: 'from-yellow-300 via-amber-100 to-yellow-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-yellow-500 to-amber-600 text-neutral-950',
      crestIcon: '🌼',
      motifStyle: 'henna-mandala',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'celebratory-banner',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 17. Prince & Princess 1st Birthday
  'little-sunshine': {
    id: 'little-sunshine',
    slug: 'little-sunshine',
    name: 'Prince & Princess 1st Birthday',
    category: 'Birthday Invitation',
    tier: 'classic',
    subtitle: 'Enchanted Kingdom Castle Gates, Confetti Pop & Golden Crown',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🎂 Bright Festive Glockenspiel Celebration Chime',
    theme: {
      style: 'little-sunshine',
      pageBg: 'bg-[#10121d]',
      cardBg: 'bg-[#1e2133]/95',
      accentBg: 'bg-gradient-to-r from-amber-400 via-yellow-400 to-orange-400',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-yellow-300',
      borderColor: 'border-amber-400/30',
      borderAccent: 'border-yellow-400/60',
      goldGradient: 'from-yellow-300 via-amber-100 to-yellow-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-400 to-yellow-500 text-black',
      crestIcon: '👑',
      motifStyle: 'fairy-castle',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'celebratory-banner',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 18. Sweet Cradle Baby Shower
  'sweet-nesting-baby': {
    id: 'sweet-nesting-baby',
    slug: 'sweet-nesting-baby',
    name: 'Sweet Cradle Baby Shower',
    category: 'Baby Shower / Naming Ceremony',
    tier: 'classic',
    subtitle: 'Golden-Lit Fluffy Cloud Wings, Golden Cradle & Lullaby',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '👶 Sweet Celestial Lullaby & Acoustic Chimes',
    theme: {
      style: 'sweet-nesting-baby',
      pageBg: 'bg-[#14081b]',
      cardBg: 'bg-[#251230]/95',
      accentBg: 'bg-gradient-to-r from-purple-500 via-pink-400 to-purple-600',
      textPrimary: 'text-purple-50',
      textSecondary: 'text-purple-200/90',
      textMuted: 'text-purple-300/70',
      textAccent: 'text-pink-200',
      borderColor: 'border-purple-500/30',
      borderAccent: 'border-pink-300/60',
      goldGradient: 'from-purple-300 via-pink-100 to-purple-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-purple-500 to-pink-500 text-white',
      crestIcon: '🍼',
      motifStyle: 'cloud-cradle',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 19. Silver & Gold Jubilee Milestone
  'silver-anniversary': {
    id: 'silver-anniversary',
    slug: 'silver-anniversary',
    name: 'Silver & Gold Jubilee Milestone',
    category: 'Anniversary & Reception',
    tier: 'classic',
    subtitle: 'Faceted Crystal Light-Refraction Gates & Milestone Laurel',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🥂 Champagne Toast Symphony & Piano Harmony',
    theme: {
      style: 'silver-anniversary',
      pageBg: 'bg-[#0a0c10]',
      cardBg: 'bg-[#151922]/95',
      accentBg: 'bg-gradient-to-r from-zinc-600 via-slate-400 to-amber-500',
      textPrimary: 'text-slate-50',
      textSecondary: 'text-slate-200/90',
      textMuted: 'text-slate-300/70',
      textAccent: 'text-amber-200',
      borderColor: 'border-slate-600/30',
      borderAccent: 'border-slate-300/60',
      goldGradient: 'from-slate-200 via-amber-100 to-slate-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-zinc-700 to-amber-700 text-slate-100',
      crestIcon: '🥂',
      motifStyle: 'crystal-facet',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 20. Goa Coastal Beachfront
  'coastal-breeze': {
    id: 'coastal-breeze',
    slug: 'coastal-breeze',
    name: 'Goa Coastal Beachfront',
    category: 'Wedding Invitation',
    tier: 'classic',
    subtitle: 'Louvered Beach Pavilion Louvers, Seashell Monogram & Ocean Wave',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🏖️ Tropical Ocean Breeze & Acoustic Harp',
    theme: {
      style: 'coastal-breeze',
      pageBg: 'bg-[#021317]',
      cardBg: 'bg-[#07242c]/95',
      accentBg: 'bg-gradient-to-r from-cyan-600 via-teal-500 to-amber-400',
      textPrimary: 'text-cyan-50',
      textSecondary: 'text-cyan-200/90',
      textMuted: 'text-cyan-300/70',
      textAccent: 'text-cyan-300',
      borderColor: 'border-cyan-600/30',
      borderAccent: 'border-cyan-400/60',
      goldGradient: 'from-cyan-300 via-amber-100 to-teal-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-cyan-600 to-teal-700 text-white',
      crestIcon: '🐚',
      motifStyle: 'coastal-waves',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },
};

export const getTemplateConfig = (templateId) => {
  const aliases = {
    // Royal aliases
    'royal-love': 'rose-gold-blush-royal',
    'royal-elegance': 'modern-minimal-royal',
    'jaipur-heritage': 'royal-heritage',
    'shahi-sangeet': 'royal-legacy',
    'royal-griha-utsav': 'royal-crest',
    'nawab-of-awadh': 'royal-grace',
    'emerald-noir': 'emerald-noir-royal',
    'crimson-royale': 'ivory-elegance-royal',
    'taj-imperial': 'royal-majesty',
    'bikaner-riyasat': 'royal-legacy',
    'udaivilas-palace': 'royal-heritage',
    'emerald-heritage': 'emerald-noir-royal',
    'majestic-love': 'modern-minimal-royal',
    'jodhpur-sun-city': 'royal-majesty',
    'mughal-courtyard': 'emerald-noir-royal',
    'royal-engagement-regal': 'rose-gold-blush-royal',
    'champagne-glamour': 'royal-legacy',
    'royal-reception-gala': 'royal-majesty',
    'vintage-rajputana': 'royal-legacy',
    'mysore-grandeur': 'royal-grace',
    'golden-jubilee-royal': 'silver-anniversary',
    'griha-pravesh': 'royal-crest',
    'botanical-eucalyptus': 'terracotta-boho',
    'pastel-peony': 'blooming-dreams',
    'celestial-starlight': 'celestial-night',
    'lavender-mist': 'sweet-nesting-baby',
    'sunset-citrus': 'mehendi-magic',
    'monochrome-chic': 'modern-minimal',
    'sweet-first-birthday': 'little-sunshine',
    'fairy-tale-princess': 'blooming-dreams',
    'baby-blessing-cradle': 'sweet-nesting-baby',
    'golden-fifty-love': 'silver-anniversary',
    'navaratna-puja': 'royal-crest',
    'minimalist-arch': 'modern-minimal',
    'royal-yuvraj-arrival': 'little-sunshine',
  };
  const resolvedId = aliases[templateId] || templateId;
  return templateRegistry[resolvedId] || templateRegistry['rose-gold-blush-royal'];
};
