/**
 * Moonlight Production - Master Template Design Registry & Configuration Engine
 * 
 * Defines the theme, colors, typography, section ordering, decorative treatments,
 * and component styles for each luxury invitation template.
 */

export const templateRegistry = {
  'royal-love': {
    id: 'royal-love',
    name: 'Royal Love',
    category: 'Wedding',
    theme: {
      style: 'royal-heritage',
      pageBg: 'bg-[#1C140E]',
      cardBg: 'bg-[#2A1D13]/90',
      accentBg: 'bg-gradient-to-r from-amber-600 via-amber-500 to-amber-700',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/80',
      textMuted: 'text-amber-300/60',
      textAccent: 'text-amber-400',
      borderColor: 'border-amber-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-amber-400 via-amber-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-500 to-amber-700 text-black',
      crestIcon: '👑',
    },
    sections: [
      'opening',
      'hero',
      'countdown',
      'story',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
      'wishes',
    ],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  'blooming-dreams': {
    id: 'blooming-dreams',
    name: 'Blooming Dreams',
    category: 'Engagement',
    theme: {
      style: 'pastel-floral',
      pageBg: 'bg-[#1F1418]',
      cardBg: 'bg-[#2E1D24]/90',
      accentBg: 'bg-gradient-to-r from-rose-500 via-rose-400 to-pink-600',
      textPrimary: 'text-rose-50',
      textSecondary: 'text-rose-200/80',
      textMuted: 'text-rose-300/60',
      textAccent: 'text-rose-300',
      borderColor: 'border-rose-500/30',
      borderAccent: 'border-rose-400/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-400 to-pink-600 text-white',
      crestIcon: '🌸',
    },
    sections: [
      'opening',
      'hero',
      'countdown',
      'story',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
    ],
    components: {
      hero: 'floral-arch',
      events: 'stacked-cards',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'rose-gold',
      rsvp: 'romantic-card',
    },
  },

  'little-sunshine': {
    id: 'little-sunshine',
    name: 'A Little Sunshine',
    category: 'Birthday',
    theme: {
      style: 'warm-amber',
      pageBg: 'bg-[#1E1710]',
      cardBg: 'bg-[#2E2014]/90',
      accentBg: 'bg-gradient-to-r from-amber-500 via-yellow-400 to-orange-500',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/80',
      textMuted: 'text-amber-300/60',
      textAccent: 'text-yellow-400',
      borderColor: 'border-amber-500/30',
      borderAccent: 'border-yellow-400/60',
      goldGradient: 'from-yellow-300 via-amber-100 to-yellow-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-yellow-400 to-amber-500 text-black',
      crestIcon: '✨',
    },
    sections: [
      'hero',
      'countdown',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
    ],
    components: {
      hero: 'celebratory-banner',
      events: 'stacked-cards',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'joyful-form',
    },
  },

  'together-forever': {
    id: 'together-forever',
    name: 'Together Forever',
    category: 'Anniversary',
    theme: {
      style: 'vintage-cream',
      pageBg: 'bg-[#181615]',
      cardBg: 'bg-[#262320]/90',
      accentBg: 'bg-gradient-to-r from-stone-400 via-amber-300 to-stone-500',
      textPrimary: 'text-stone-50',
      textSecondary: 'text-stone-200/80',
      textMuted: 'text-stone-400',
      textAccent: 'text-amber-300',
      borderColor: 'border-stone-600/30',
      borderAccent: 'border-amber-400/50',
      goldGradient: 'from-stone-200 via-amber-100 to-stone-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-stone-300 to-amber-400 text-black',
      crestIcon: '💍',
    },
    sections: [
      'opening',
      'hero',
      'countdown',
      'story',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
    ],
    components: {
      hero: 'timeless-portrait',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'classic-card',
    },
  },

  'emerald-heritage': {
    id: 'emerald-heritage',
    name: 'Emerald Heritage',
    category: 'Wedding',
    theme: {
      style: 'mughal-emerald',
      pageBg: 'bg-[#0E1A14]',
      cardBg: 'bg-[#14281E]/90',
      accentBg: 'bg-gradient-to-r from-emerald-600 via-teal-500 to-emerald-700',
      textPrimary: 'text-emerald-50',
      textSecondary: 'text-emerald-200/80',
      textMuted: 'text-emerald-300/60',
      textAccent: 'text-emerald-300',
      borderColor: 'border-emerald-600/30',
      borderAccent: 'border-emerald-400/60',
      goldGradient: 'from-emerald-300 via-amber-200 to-emerald-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-emerald-400 to-teal-500 text-black',
      crestIcon: '⚜️',
    },
    sections: [
      'opening',
      'hero',
      'countdown',
      'story',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
    ],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  'celestial-night': {
    id: 'celestial-night',
    name: 'Celestial Night',
    category: 'Save the Date',
    theme: {
      style: 'midnight-starlight',
      pageBg: 'bg-[#0E101D]',
      cardBg: 'bg-[#15192E]/90',
      accentBg: 'bg-gradient-to-r from-indigo-500 via-purple-500 to-blue-600',
      textPrimary: 'text-indigo-50',
      textSecondary: 'text-indigo-200/80',
      textMuted: 'text-indigo-300/60',
      textAccent: 'text-indigo-300',
      borderColor: 'border-indigo-500/30',
      borderAccent: 'border-indigo-400/60',
      goldGradient: 'from-indigo-200 via-purple-100 to-blue-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-indigo-400 to-purple-500 text-white',
      crestIcon: '🌙',
    },
    sections: [
      'hero',
      'countdown',
      'events',
      'gallery',
      'things_to_know',
      'scratch_card',
      'rsvp',
    ],
    components: {
      hero: 'midnight-stars',
      events: 'stacked-cards',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'modern-card',
    },
  },
};

export const getTemplateConfig = (templateId) => {
  return templateRegistry[templateId] || templateRegistry['royal-love'];
};
