/**
 * Moonlight Production - Master Template Design Registry & Configuration Engine
 * 
 * Defines the theme, colors, typography, section ordering, decorative treatments,
 * and component styles for the 20 distinct invitation suites (10 Royal + 10 Classic).
 */

export const templateRegistry = {
  // =========================================================================
  // 👑 10 ROYAL TIER SUITES
  // =========================================================================

  // 1. The Rajwada Palace Suite
  'royal-love': {
    id: 'royal-love',
    slug: 'royal-love',
    name: 'The Rajwada Palace Suite',
    category: 'Wedding Invitation',
    subtitle: 'Deep Crimson, Antique Gold Foil & Rajputana Carved Palace Doors',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🎺 Royal Shehnai & Sitar Serenade',
    theme: {
      style: 'royal-heritage',
      pageBg: 'bg-[#1C140E]',
      cardBg: 'bg-[#2A1D13]/95',
      accentBg: 'bg-gradient-to-r from-amber-600 via-amber-500 to-amber-700',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-amber-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-amber-400 via-amber-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-500 to-amber-700 text-black',
      crestIcon: '👑',
      motifStyle: 'rajwada-carved',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 2. Emerald Noir & Dynasty
  'emerald-noir': {
    id: 'emerald-noir',
    slug: 'emerald-noir',
    name: 'Emerald Noir & Dynasty',
    category: 'Wedding Invitation',
    subtitle: 'Imperial Emerald Green, Backlit Mughal Jaali & Gold Dynasty',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3574c82c3.mp3?filename=indian-classical-instrumental-110825.mp3',
    musicTitle: '🪈 Mughal Flute & Santoor Symphony',
    theme: {
      style: 'emerald-noir',
      pageBg: 'bg-[#031910]',
      cardBg: 'bg-[#072a1b]/95',
      accentBg: 'bg-gradient-to-r from-emerald-600 via-emerald-500 to-teal-700',
      textPrimary: 'text-emerald-50',
      textSecondary: 'text-emerald-200/90',
      textMuted: 'text-emerald-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-emerald-600/30',
      borderAccent: 'border-emerald-500/60',
      goldGradient: 'from-emerald-400 via-teal-200 to-amber-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-emerald-500 to-teal-700 text-amber-200',
      crestIcon: '✨',
      motifStyle: 'jaali',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'emerald-foil',
      rsvp: 'royal-suite',
    },
  },

  // 3. Crimson Royale & Velvet
  'crimson-royale': {
    id: 'crimson-royale',
    slug: 'crimson-royale',
    name: 'Crimson Royale & Velvet',
    category: 'Wedding Invitation',
    subtitle: 'Rich Ruby Velvet, Gold Cord Tassels & Royal Grandeur',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🎻 Royal Philharmonic Sitar Symphony',
    theme: {
      style: 'crimson-royale',
      pageBg: 'bg-[#200308]',
      cardBg: 'bg-[#3b0914]/95',
      accentBg: 'bg-gradient-to-r from-rose-700 via-red-600 to-amber-600',
      textPrimary: 'text-rose-50',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-amber-400',
      borderColor: 'border-rose-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-rose-400 via-amber-200 to-rose-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-600 to-amber-600 text-white',
      crestIcon: '👑',
      motifStyle: 'velvet-damask',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 4. Lake Palace Pichola Suite
  'udaivilas-palace': {
    id: 'udaivilas-palace',
    slug: 'udaivilas-palace',
    name: 'Lake Palace Pichola Suite',
    category: 'Wedding Invitation',
    subtitle: 'Midnight Sapphire Waters, Starry Reflections & Palace Arches',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🌊 Serene Lakeside Palace Chimes & Flute',
    theme: {
      style: 'udaivilas-palace',
      pageBg: 'bg-[#060D1F]',
      cardBg: 'bg-[#0F1B38]/95',
      accentBg: 'bg-gradient-to-r from-blue-700 via-indigo-600 to-amber-500',
      textPrimary: 'text-sky-50',
      textSecondary: 'text-sky-200/90',
      textMuted: 'text-sky-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-sky-600/30',
      borderAccent: 'border-amber-400/60',
      goldGradient: 'from-sky-400 via-amber-200 to-indigo-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-sky-600 to-indigo-800 text-amber-200',
      crestIcon: '🏰',
      motifStyle: 'pichola-waves',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 5. Jaipur Pink City Haveli
  'jaipur-heritage': {
    id: 'jaipur-heritage',
    slug: 'jaipur-heritage',
    name: 'Jaipur Pink City Haveli',
    category: 'Wedding Invitation',
    subtitle: 'Sandstone Jharokhas, Royal Peacock & Marigold Torans',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🦚 Jaipur Nagada, Sitar & Shehnai Utsav',
    theme: {
      style: 'jaipur-heritage',
      pageBg: 'bg-[#23080e]',
      cardBg: 'bg-[#3b1219]/95',
      accentBg: 'bg-gradient-to-r from-rose-700 via-orange-600 to-amber-500',
      textPrimary: 'text-rose-50',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-rose-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-rose-400 via-amber-200 to-orange-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-600 to-amber-600 text-white',
      crestIcon: '🦚',
      motifStyle: 'jharokha-arch',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 6. Shahi Sangeet & Musical Night
  'shahi-sangeet': {
    id: 'shahi-sangeet',
    slug: 'shahi-sangeet',
    name: 'Shahi Sangeet & Musical Night',
    category: 'Wedding Invitation',
    subtitle: 'Magenta Velvet Stage Curtains & High-Energy Celebration',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=energy-10657.mp3',
    musicTitle: '💃 High-Energy Sangeet & Dholak Beats',
    theme: {
      style: 'shahi-sangeet',
      pageBg: 'bg-[#1a0312]',
      cardBg: 'bg-[#330722]/95',
      accentBg: 'bg-gradient-to-r from-fuchsia-600 via-pink-600 to-amber-400',
      textPrimary: 'text-pink-50',
      textSecondary: 'text-pink-200/90',
      textMuted: 'text-pink-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-fuchsia-600/30',
      borderAccent: 'border-pink-500/60',
      goldGradient: 'from-fuchsia-400 via-pink-200 to-amber-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-fuchsia-600 to-pink-600 text-white',
      crestIcon: '🎵',
      motifStyle: 'festive-curtain',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'celebratory-banner',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 7. The Nawabi Awadh Suite
  'nawab-of-awadh': {
    id: 'nawab-of-awadh',
    slug: 'nawab-of-awadh',
    name: 'The Nawabi Awadh Suite',
    category: 'Wedding Invitation',
    subtitle: 'Persian Filigree Arches, Turquoise Silk & Royal Crescent',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3574c82c3.mp3?filename=indian-classical-instrumental-110825.mp3',
    musicTitle: '✨ Awadhi Classical Sitar & Ghazal Harmony',
    theme: {
      style: 'nawab-of-awadh',
      pageBg: 'bg-[#021212]',
      cardBg: 'bg-[#082b2b]/95',
      accentBg: 'bg-gradient-to-r from-teal-600 via-emerald-600 to-amber-400',
      textPrimary: 'text-teal-50',
      textSecondary: 'text-teal-200/90',
      textMuted: 'text-teal-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-teal-600/30',
      borderAccent: 'border-teal-400/60',
      goldGradient: 'from-teal-300 via-amber-200 to-teal-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-teal-600 to-emerald-700 text-amber-200',
      crestIcon: '🌙',
      motifStyle: 'awadh-arch',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 8. Sacred Swarna Griha Pravesh
  'royal-griha-utsav': {
    id: 'royal-griha-utsav',
    slug: 'royal-griha-utsav',
    name: 'Sacred Swarna Griha Pravesh',
    category: 'Housewarming / Griha Pravesh',
    subtitle: 'Solid Teak Temple Doors, Brass Bells & Kalash Shubh Labh',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🪔 Sacred Vedic Chant & Temple Bells',
    theme: {
      style: 'royal-griha-utsav',
      pageBg: 'bg-[#1a0702]',
      cardBg: 'bg-[#301105]/95',
      accentBg: 'bg-gradient-to-r from-orange-600 via-amber-500 to-yellow-600',
      textPrimary: 'text-orange-50',
      textSecondary: 'text-orange-200/90',
      textMuted: 'text-orange-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-orange-600/30',
      borderAccent: 'border-amber-500/60',
      goldGradient: 'from-orange-400 via-amber-200 to-yellow-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-orange-600 to-amber-600 text-white',
      crestIcon: '🪔',
      motifStyle: 'temple-kalash',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 9. Taj Imperial Marble Suite
  'taj-imperial': {
    id: 'taj-imperial',
    slug: 'taj-imperial',
    name: 'Taj Imperial Marble Suite',
    category: 'Wedding Invitation',
    subtitle: 'Makrana White Marble Slabs & Inlaid Pietra Dura Lotus',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🏛️ Serene Grand Piano & Crystal Symphony',
    theme: {
      style: 'taj-imperial',
      pageBg: 'bg-[#0c1015]',
      cardBg: 'bg-[#18212b]/95',
      accentBg: 'bg-gradient-to-r from-slate-600 via-slate-400 to-zinc-600',
      textPrimary: 'text-slate-50',
      textSecondary: 'text-slate-200/90',
      textMuted: 'text-slate-300/70',
      textAccent: 'text-amber-300',
      borderColor: 'border-slate-500/30',
      borderAccent: 'border-slate-300/60',
      goldGradient: 'from-slate-200 via-white to-slate-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-slate-700 to-zinc-800 text-slate-100',
      crestIcon: '🏛️',
      motifStyle: 'marble-inlay',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 10. Bikaner Riyasat Fortress
  'bikaner-riyasat': {
    id: 'bikaner-riyasat',
    slug: 'bikaner-riyasat',
    name: 'Bikaner Riyasat Fortress',
    category: 'Wedding Invitation',
    subtitle: 'Studded Fortress Doors, Antique Brass Knockers & Sunburst Crest',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-wedding-113828.mp3',
    musicTitle: '🛡️ Grand Rajputana Trumpet & Royal Fanfare',
    theme: {
      style: 'bikaner-riyasat',
      pageBg: 'bg-[#140a03]',
      cardBg: 'bg-[#2b1708]/95',
      accentBg: 'bg-gradient-to-r from-amber-700 via-yellow-600 to-amber-600',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-yellow-300',
      borderColor: 'border-amber-700/30',
      borderAccent: 'border-yellow-500/60',
      goldGradient: 'from-amber-400 via-yellow-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-600 to-yellow-600 text-black',
      crestIcon: '🛡️',
      motifStyle: 'fortress-spikes',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // =========================================================================
  // 🌸 10 CLASSIC TIER SUITES
  // =========================================================================

  // 11. Pastel Floral Symphony
  'blooming-dreams': {
    id: 'blooming-dreams',
    slug: 'blooming-dreams',
    name: 'Pastel Floral Symphony',
    category: 'Engagement Invitation',
    subtitle: 'Soft Rose Quartz, Champagne Gold & Botanical Envelope Bloom',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🎻 Romantic Acoustic Guitar & Violin',
    theme: {
      style: 'pastel-floral',
      pageBg: 'bg-[#1F1418]',
      cardBg: 'bg-[#2E1D24]/95',
      accentBg: 'bg-gradient-to-r from-rose-500 via-rose-400 to-pink-600',
      textPrimary: 'text-rose-50',
      textSecondary: 'text-rose-200/90',
      textMuted: 'text-rose-300/70',
      textAccent: 'text-rose-300',
      borderColor: 'border-rose-500/30',
      borderAccent: 'border-rose-400/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-rose-400 to-pink-600 text-white',
      crestIcon: '🌸',
      motifStyle: 'floral-wreath',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 12. Modern Minimalist Luxe
  'modern-minimal': {
    id: 'modern-minimal',
    slug: 'modern-minimal',
    name: 'Modern Minimalist Luxe',
    category: 'Wedding Invitation',
    subtitle: 'Frosted Glass Sliding Panels, Crisp Typography & Monogram',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🎹 Crisp Minimalist Piano & Ambient Strings',
    theme: {
      style: 'modern-minimal',
      pageBg: 'bg-[#0f1115]',
      cardBg: 'bg-[#181b22]/95',
      accentBg: 'bg-gradient-to-r from-zinc-700 via-slate-600 to-zinc-800',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-zinc-200/90',
      textMuted: 'text-zinc-300/70',
      textAccent: 'text-amber-200',
      borderColor: 'border-zinc-700/30',
      borderAccent: 'border-zinc-400/60',
      goldGradient: 'from-zinc-300 via-white to-zinc-400',
      fontHeading: 'font-sans',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-zinc-700 to-stone-800 text-white',
      crestIcon: '💎',
      motifStyle: 'geometric-diamond',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 13. Rose Gold Botanical Ribbon
  'rose-gold-blush': {
    id: 'rose-gold-blush',
    slug: 'rose-gold-blush',
    name: 'Rose Gold Botanical Ribbon',
    category: 'Engagement Invitation',
    subtitle: 'Silk Satin Ribbon Untie, Rose Gold Heart & Romantic Chords',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '💕 Soft Romantic Acoustic Strings & Harp',
    theme: {
      style: 'rose-gold-blush',
      pageBg: 'bg-[#180a12]',
      cardBg: 'bg-[#29121f]/95',
      accentBg: 'bg-gradient-to-r from-pink-500 via-rose-400 to-rose-600',
      textPrimary: 'text-pink-50',
      textSecondary: 'text-pink-200/90',
      textMuted: 'text-pink-300/70',
      textAccent: 'text-rose-200',
      borderColor: 'border-pink-500/30',
      borderAccent: 'border-rose-300/60',
      goldGradient: 'from-rose-300 via-pink-100 to-rose-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-pink-500 to-rose-600 text-white',
      crestIcon: '💖',
      motifStyle: 'silk-ribbon',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 14. Celestial Starlight Galaxy
  'celestial-night': {
    id: 'celestial-night',
    slug: 'celestial-night',
    name: 'Celestial Starlight Galaxy',
    category: 'Wedding Invitation',
    subtitle: 'Constellation Sphere Split, Glowing Stardust & Crescent Moon',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '✨ Cosmic Crystal Shimmer & Ambient Bells',
    theme: {
      style: 'celestial-night',
      pageBg: 'bg-[#050b1b]',
      cardBg: 'bg-[#0d1730]/95',
      accentBg: 'bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-600',
      textPrimary: 'text-sky-50',
      textSecondary: 'text-sky-200/90',
      textMuted: 'text-sky-300/70',
      textAccent: 'text-sky-300',
      borderColor: 'border-sky-500/30',
      borderAccent: 'border-sky-400/60',
      goldGradient: 'from-sky-300 via-indigo-100 to-purple-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-sky-500 to-indigo-700 text-white',
      crestIcon: '🌙',
      motifStyle: 'constellation-stars',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 15. Bohemian Terracotta & Sage
  'terracotta-boho': {
    id: 'terracotta-boho',
    slug: 'terracotta-boho',
    name: 'Bohemian Terracotta & Sage',
    category: 'Wedding Invitation',
    subtitle: 'Artisanal Linen Tri-Fold, Terracotta Stamp & Palm Sprig',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🌿 Warm Rustic Acoustic Strings & Windchimes',
    theme: {
      style: 'terracotta-boho',
      pageBg: 'bg-[#1c100a]',
      cardBg: 'bg-[#301a11]/95',
      accentBg: 'bg-gradient-to-r from-amber-700 via-orange-600 to-stone-600',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-orange-300',
      borderColor: 'border-amber-700/30',
      borderAccent: 'border-orange-500/60',
      goldGradient: 'from-amber-400 via-orange-200 to-amber-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-700 to-orange-700 text-white',
      crestIcon: '🌿',
      motifStyle: 'boho-palm',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'heritage-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 16. Marigold Henna Utsav
  'mehendi-magic': {
    id: 'mehendi-magic',
    slug: 'mehendi-magic',
    name: 'Marigold Henna Utsav',
    category: 'Wedding Invitation',
    subtitle: 'Kaleidoscopic Henna Mandala Bloom, Marigold & Dholak',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=energy-10657.mp3',
    musicTitle: '🌼 Joyful Folk Bells & Mehendi Dholak Beats',
    theme: {
      style: 'mehendi-magic',
      pageBg: 'bg-[#1f1001]',
      cardBg: 'bg-[#331c03]/95',
      accentBg: 'bg-gradient-to-r from-yellow-500 via-amber-500 to-orange-500',
      textPrimary: 'text-yellow-50',
      textSecondary: 'text-yellow-200/90',
      textMuted: 'text-yellow-300/70',
      textAccent: 'text-yellow-300',
      borderColor: 'border-yellow-500/30',
      borderAccent: 'border-amber-400/60',
      goldGradient: 'from-yellow-300 via-amber-100 to-yellow-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-yellow-500 to-amber-600 text-neutral-950',
      crestIcon: '🌼',
      motifStyle: 'henna-mandala',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'celebratory-banner',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 17. Prince & Princess 1st Birthday
  'little-sunshine': {
    id: 'little-sunshine',
    slug: 'little-sunshine',
    name: 'Prince & Princess 1st Birthday',
    category: 'Birthday Invitation',
    subtitle: 'Enchanted Kingdom Castle Gates, Confetti Pop & Golden Crown',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🎂 Bright Festive Glockenspiel Celebration Chime',
    theme: {
      style: 'little-sunshine',
      pageBg: 'bg-[#10121d]',
      cardBg: 'bg-[#1e2133]/95',
      accentBg: 'bg-gradient-to-r from-amber-400 via-yellow-400 to-orange-400',
      textPrimary: 'text-amber-50',
      textSecondary: 'text-amber-200/90',
      textMuted: 'text-amber-300/70',
      textAccent: 'text-yellow-300',
      borderColor: 'border-amber-400/30',
      borderAccent: 'border-yellow-400/60',
      goldGradient: 'from-yellow-300 via-amber-100 to-yellow-500',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-amber-400 to-yellow-500 text-black',
      crestIcon: '👑',
      motifStyle: 'fairy-castle',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'celebratory-banner',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },

  // 18. Sweet Cradle Baby Shower
  'sweet-nesting-baby': {
    id: 'sweet-nesting-baby',
    slug: 'sweet-nesting-baby',
    name: 'Sweet Cradle Baby Shower',
    category: 'Baby Shower / Naming Ceremony',
    subtitle: 'Golden-Lit Fluffy Cloud Wings, Golden Cradle & Lullaby',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '👶 Sweet Celestial Lullaby & Acoustic Chimes',
    theme: {
      style: 'sweet-nesting-baby',
      pageBg: 'bg-[#14081b]',
      cardBg: 'bg-[#251230]/95',
      accentBg: 'bg-gradient-to-r from-purple-500 via-pink-400 to-purple-600',
      textPrimary: 'text-purple-50',
      textSecondary: 'text-purple-200/90',
      textMuted: 'text-purple-300/70',
      textAccent: 'text-pink-200',
      borderColor: 'border-purple-500/30',
      borderAccent: 'border-pink-300/60',
      goldGradient: 'from-purple-300 via-pink-100 to-purple-400',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-purple-500 to-pink-500 text-white',
      crestIcon: '🍼',
      motifStyle: 'cloud-cradle',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'floral-foil',
      rsvp: 'royal-suite',
    },
  },

  // 19. Silver & Gold Jubilee Milestone
  'silver-anniversary': {
    id: 'silver-anniversary',
    slug: 'silver-anniversary',
    name: 'Silver & Gold Jubilee Milestone',
    category: 'Anniversary & Reception',
    subtitle: 'Faceted Crystal Light-Refraction Gates & Milestone Laurel',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=piano-moment-9835.mp3',
    musicTitle: '🥂 Champagne Toast Symphony & Piano Harmony',
    theme: {
      style: 'silver-anniversary',
      pageBg: 'bg-[#0a0c10]',
      cardBg: 'bg-[#151922]/95',
      accentBg: 'bg-gradient-to-r from-zinc-600 via-slate-400 to-amber-500',
      textPrimary: 'text-slate-50',
      textSecondary: 'text-slate-200/90',
      textMuted: 'text-slate-300/70',
      textAccent: 'text-amber-200',
      borderColor: 'border-slate-600/30',
      borderAccent: 'border-slate-300/60',
      goldGradient: 'from-slate-200 via-amber-100 to-slate-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-zinc-700 to-amber-700 text-slate-100',
      crestIcon: '🥂',
      motifStyle: 'crystal-facet',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'cinematic-crest',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'silver-foil',
      rsvp: 'royal-suite',
    },
  },

  // 20. Goa Coastal Beachfront
  'coastal-breeze': {
    id: 'coastal-breeze',
    slug: 'coastal-breeze',
    name: 'Goa Coastal Beachfront',
    category: 'Wedding Invitation',
    subtitle: 'Louvered Beach Pavilion Louvers, Seashell Monogram & Ocean Wave',
    musicPreset: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=acoustic-guitars-ambient-uplifting-11369.mp3',
    musicTitle: '🏖️ Tropical Ocean Breeze & Acoustic Harp',
    theme: {
      style: 'coastal-breeze',
      pageBg: 'bg-[#021317]',
      cardBg: 'bg-[#07242c]/95',
      accentBg: 'bg-gradient-to-r from-cyan-600 via-teal-500 to-amber-400',
      textPrimary: 'text-cyan-50',
      textSecondary: 'text-cyan-200/90',
      textMuted: 'text-cyan-300/70',
      textAccent: 'text-cyan-300',
      borderColor: 'border-cyan-600/30',
      borderAccent: 'border-cyan-400/60',
      goldGradient: 'from-cyan-300 via-amber-100 to-teal-300',
      fontHeading: 'font-serif',
      fontScript: 'font-serif italic',
      fontBody: 'font-sans',
      foilBadge: 'bg-gradient-to-r from-cyan-600 to-teal-700 text-white',
      crestIcon: '🐚',
      motifStyle: 'coastal-waves',
    },
    sections: ['opening', 'hero', 'countdown', 'story', 'events', 'gallery', 'things_to_know', 'scratch_card', 'rsvp'],
    components: {
      hero: 'floral-arch',
      events: 'timeline',
      gallery: 'carousel-lightbox',
      things_to_know: 'luxury-cards',
      scratch: 'gold-foil',
      rsvp: 'royal-suite',
    },
  },
};

export const getTemplateConfig = (templateId) => {
  const aliases = {
    // Backwards compatibility aliases for older links
    'emerald-heritage': 'emerald-noir',
    'majestic-love': 'royal-love',
    'jodhpur-sun-city': 'udaivilas-palace',
    'mughal-courtyard': 'emerald-noir',
    'royal-engagement-regal': 'blooming-dreams',
    'champagne-glamour': 'royal-love',
    'royal-reception-gala': 'udaivilas-palace',
    'vintage-rajputana': 'bikaner-riyasat',
    'mysore-grandeur': 'nawab-of-awadh',
    'golden-jubilee-royal': 'silver-anniversary',
    'griha-pravesh': 'royal-griha-utsav',
    'botanical-eucalyptus': 'terracotta-boho',
    'pastel-peony': 'blooming-dreams',
    'celestial-starlight': 'celestial-night',
    'lavender-mist': 'sweet-nesting-baby',
    'sunset-citrus': 'mehendi-magic',
    'monochrome-chic': 'modern-minimal',
    'sweet-first-birthday': 'little-sunshine',
    'fairy-tale-princess': 'blooming-dreams',
    'baby-blessing-cradle': 'sweet-nesting-baby',
    'golden-fifty-love': 'silver-anniversary',
    'navaratna-puja': 'royal-griha-utsav',
    'minimalist-arch': 'modern-minimal',
    'royal-yuvraj-arrival': 'little-sunshine',
  };
  const resolvedId = aliases[templateId] || templateId;
  return templateRegistry[resolvedId] || templateRegistry['royal-love'];
};
